version: '3.7'

services:
  orangehrm:
    image: orangehrm/orangehrm:latest
    container_name: orangehrm
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=orangehrm
      - MYSQL_USER=orangeuser
      - MYSQL_PASSWORD=orangepass
      - MYSQL_ROOT_PASSWORD=rootpass
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: orangehrm-db
    environment:
      - MYSQL_DATABASE=orangehrm
      - MYSQL_USER=orangeuser
      - MYSQL_PASSWORD=orangepass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
